// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestArtworkPricingFormula2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testArtworkPricingFormula2() {
    driver.get("https://www.artismycareer.com/pricing-calculator/");
    driver.manage().window().setSize(new Dimension(1486, 794));
    driver.findElement(By.cssSelector(".camper1CalculatorRightContainer > .camper1CalculatorItemContainer:nth-child(2)")).click();
    driver.findElement(By.id("wage")).click();
    driver.findElement(By.id("wage")).sendKeys("9");
    driver.findElement(By.id("time")).click();
    driver.findElement(By.id("time")).sendKeys("48");
    driver.findElement(By.id("acost")).click();
    driver.findElement(By.id("acost")).sendKeys("56");
    driver.findElement(By.id("cb")).click();
    assertThat(driver.findElement(By.id("c2")).getText(), is("£976"));
  }
}
